### ISSUE TITLE
spark-and-python-for-big-data-with-pyspark

### ISSUE THREAD

**Issue by GCPBigData** [bhishanpdl/Feature_Engineering#1]
https://www.udemy.com/course/spark-and-python-for-big-data-with-pyspark/?xref=wish&courseId=980798

Are these the course files from Udemy?

**Comment by bhishanpdl** [comment]
@GCPBigData Good observation. Some of the materials here in this repo are inspired from that course I took. The course is much helpful transitioning from python (pandas) to big data world (using pyspark).
